# Generated by Django 5.0 on 2026-01-20 10:21

import django.db.models.deletion
import tasks.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Task title (max 200 chars)",
                        max_length=200,
                        validators=[tasks.validators.validate_title_length],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Task description (max 2000 chars)",
                        max_length=2000,
                        validators=[tasks.validators.validate_description_length],
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Task due date (optional)", null=True
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Media"),
                            ("baja", "Baja"),
                        ],
                        db_index=True,
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("completada", "Completada"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when task was completed",
                        null=True,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Task owner (immutable)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tasks_task",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="tasks_task_owner_i_35cb9a_idx",
                    ),
                    models.Index(
                        fields=["owner", "status"], name="tasks_task_owner_i_9240ec_idx"
                    ),
                    models.Index(
                        fields=["owner", "priority"],
                        name="tasks_task_owner_i_a5b9b0_idx",
                    ),
                    models.Index(
                        fields=["owner", "due_date"],
                        name="tasks_task_owner_i_3addd0_idx",
                    ),
                ],
            },
        ),
    ]
