# Generated by Django 5.0.4 on 2026-01-21 10:58

from django.db import migrations, models


def translate_status_priority(apps, schema_editor):
    """Translate existing Spanish values to English."""
    Task = apps.get_model('tasks', 'Task')
    
    # Status translations
    status_map = {
        'pendiente': 'pending',
        'completada': 'completed',
    }
    
    # Priority translations
    priority_map = {
        'alta': 'high',
        'media': 'medium',
        'baja': 'low',
    }
    
    # Update all tasks
    for task in Task.objects.all():
        updated = False
        
        if task.status in status_map:
            task.status = status_map[task.status]
            updated = True
        
        if task.priority in priority_map:
            task.priority = priority_map[task.priority]
            updated = True
        
        if updated:
            task.save(update_fields=['status', 'priority'])


def reverse_translate(apps, schema_editor):
    """Reverse translation for rollback."""
    Task = apps.get_model('tasks', 'Task')
    
    # Reverse translations
    status_map = {
        'pending': 'pendiente',
        'completed': 'completada',
    }
    
    priority_map = {
        'high': 'alta',
        'medium': 'media',
        'low': 'baja',
    }
    
    for task in Task.objects.all():
        updated = False
        
        if task.status in status_map:
            task.status = status_map[task.status]
            updated = True
        
        if task.priority in priority_map:
            task.priority = priority_map[task.priority]
            updated = True
        
        if updated:
            task.save(update_fields=['status', 'priority'])


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(translate_status_priority, reverse_translate),
        # Then, alter the field definitions
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=15),
        ),
    ]
