# Generated by Django 5.0 on 2026-01-20 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(help_text="Original filename", max_length=255),
                ),
                (
                    "blob_name",
                    models.CharField(
                        help_text="Unique blob name in Azure storage",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="File size in bytes",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "content_type",
                    models.CharField(help_text="MIME type of the file", max_length=100),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Upload timestamp"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Task this attachment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tasks.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "-created_at"],
                        name="attachments_task_id_0086dd_idx",
                    ),
                    models.Index(
                        fields=["blob_name"], name="attachments_blob_na_ee2ccc_idx"
                    ),
                ],
            },
        ),
    ]
